project:
  type: book
  output-dir: docs

book:
  title: "社会調査のためのR入門"
  author: "藤原翔（東京大学社会科学研究所）"
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - pipe.qmd
    - data.qmd
    - variables.qmd
    - quarto.qmd
    - tips.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    
crossref:
  fig-title: 図     # (default is "Figure")
  tbl-title: 表     # (default is "Table")
  title-delim: "："     # (default is ":")