# 本資料の説明 {.unnumbered}

社会調査のためのRの入門についての資料です．

## 目的

学部，大学院，そして研究職についてからも様々なSのつく統計ソフトを使ってきました．
私が学部の頃はRの入門書も限られていました．
しかし，世界中の開発者やユーザーのおかげで，また特にRStudioや`tidyverse`などによってRが格段に利用しやすくなりました．

研究や授業でRを使用することが多くなったため，メモとしてこの資料を作成しましたが，せっかくなので公開します．

基本的には社会調査データの分析を前提とした統計手法や例を用います．データは実際に行われた社会調査のデータをもとに作成されたものを利用します．

プログラミング初心者でRの操作にもそもそも不慣れな筆者だからこそ，初学者に分かりやすく伝えられる部分もあるかもしれません．

もちろん簡単なRの操作だけで終わるのはもったいないです．
様々なRの機能をフル活用することで，良い分析や図示などが可能になります．
Rによって美しくインパクトのある図を描くことや最先端のモデルを用いた分析が可能です．

データ図示（Data Visualization）は規則性やパターンを確かめたり発見したりするための重要な方法です．




## 表記上の注意

パッケージについては`パッケージ名`パッケージ，
関数については関数の名前の後に丸括弧をつけて，`関数名()`と示す．例えば`tidyverse`というパッケージは`tidyverse`パッケージ，`summarise`という関数は`summarise()`と示す．`()`がついていれば関数である．
特定のパッケージの関数やオブジェクトであることを明記するために`パッケージ名::関数名()`や`パッケージ名::オブジェクト名`とすることもある．例えば`dplyr::summarise()`や`AER::GSS7402`と示す．

その他，オブジェクトなどはaやGSS7402ではなく`a`や`GSS7402`のように示す．括弧は必要ない．

::: {.callout-tip}
## ポイント
ここにポイントを記入します．ポイントは読み飛ばしても大丈夫です．
:::

::: {.callout-warning}
## 注意点
ここに注意点を記入します．
:::


